version: '3.3'
services:
    shiny:
        image: rocker/shiny-verse
        restart: always
        ports:
            - '80:3838'
        environment:
        - APPLICATION_LOGS_TO_STDOUT=false
        volumes:
            - ./apps:/srv/shiny-server
            - ./shiny-server.log:/var/log/shiny-server.log